### ISSUE TITLE
Avoid the access to private information by anonymous users

### ISSUE THREAD

**Issue by fjlopez** [IAAA-Lab/pid-ms#8]
**Namespace details**
- [x] Hide all details of non public namespaces 
- [x] Hide in public namespaces, the public namespace flag and the source details

**Namespaces**
- [x] Hide rows of non public namespaces in rows

**Task details**
- [x] Restrict access to authorised people

**Tasks**
- [x] Do not show the link

**Change details**
- [x] Restrict access to authorised people

**Changes**
- [x] Do not show links to task and change details

**Persistent Identifier**
- [x] Hide process status
